---
- name: Uninstall current installation of yazi
  block:
    - name: Uninstall yazi OS-specifically from package manager
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - "{{ role_path }}/tasks/noauto_uninstall_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_uninstall_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_uninstall_{{ ansible_distribution }}.yml"
        - "{{ role_path }}/tasks/noauto_uninstall_{{ ansible_os_family }}.yml"
        - "{{ role_path }}/tasks/noauto_uninstall_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: task_file

    - name: Import installed yazi version check
      ansible.builtin.include_tasks: noauto_check_installed_version.yml

    - name: Uninstall yazi from source
      ansible.builtin.include_tasks: noauto_uninstall_source.yml
      when: yazi_installed_version is defined and yazi_installed_version != ""
