---
- name: Uninstall yazi from source
  block:
    - name: Include rustup role
      ansible.builtin.include_role:
        name: "{{ yazi_rustup_role }}"

    - name: Uninstall yazi
      ansible.builtin.command:
        cmd: "cargo uninstall yazi"
      environment:
        PATH: "{{ yazi_cargo_dir }}/bin:{{ ansible_env.PATH }}"
      failed_when: false
      ignore_errors: true
      register: alacirty_uninstall_cargo_cmd
      changed_when: "'Removing' in yazi_uninstall_cargo_cmd.stdout"
      become: "{{ true if yazi_become_user else false }}"
      become_user: "{{ yazi_become_user }}"
