---
- name: Converge
  hosts: all

  vars:
    ansible_user: root

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.yazi
